### ISSUE TITLE
fix invalid date format.

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#47] opened 2023-07-11 11:41 UTC
So that we'd be able to filter events based on their dates. 

All dates should follow this sequence: **day, month date, year**. An example is: **Saturday, April 15, 2023**

On the client-side, we're using [dayjs](https://www.npmjs.com/package/dayjs) to format the date strings we have, and improper dates will return the "invalid date" string.

Start from this entry (below) and look for other occurrences that do not meet the aforementioned format.

https://github.com/kaf-lamed-beyt/ng-tech-events/blob/5696cae0618d9e5cb055d4542b7100540d9f08b9/README.md#L33-L34

The entries that have "to be announced" can be ignored. We'll look for a way to bypass it at the client.

**Comment by DeveloperAspire** [comment] 2023-07-11 11:55
@kaf-lamed-beyt  Boss, can I take on this?

**Comment by kaf-lamed-beyt** [comment] 2023-07-11 11:57
Assigning you now, my chief!! 🚀

**Comment by DeveloperAspire** [comment] 2023-07-11 12:19
@kaf-lamed-beyt  Thank you Chief.

If you don't mind, I could use some help on more context and explanation, although I did grasp what the issue is about I still need a little more clarifications, if you can help with that my bro

**Comment by kaf-lamed-beyt** [comment] 2023-07-11 14:04
Yeah yeah... that's exactly it.

**Comment by kaf-lamed-beyt** [comment] 2023-07-11 15:35
> I have a question tho? are you rendering the markdown to the Frontend?

Yes, that's exactly what I'm doing 😃

- fetch the markdown content via GitHub's API
- parse the content 
- match the table syntaxes with RegEx (gave ChatGPT some instructions for the exprression) and filter what we need. 
- return an array of event objects

**Comment by PrimeFord** [comment] 2023-07-12 08:33
if you don't min chief.... I'd like to join on this task

**Comment by yhoungdev** [comment] 2023-07-12 08:39
@kaf-lamed-beyt i think you should setup a Github action that lets people assign an issue to them self, when they type a specific command. 

so others can see that the task has been assigned

**Comment by DeveloperAspire** [comment] 2023-07-12 08:54
@kaf-lamed-beyt you can reassign it to @PrimeFord let him work on it. I will find some other issue.

**Comment by PrimeFord** [comment] 2023-07-12 09:00
![screen](https://github.com/kaf-lamed-beyt/ng-tech-events/assets/115805335/9c204e9e-5087-4b84-85fa-e777a3aa4a49)

**Comment by PrimeFord** [comment] 2023-07-12 09:01
> ![screen](https://user-images.githubusercontent.com/115805335/252915384-9c204e9e-5087-4b84-85fa-e777a3aa4a49.png)

check this out bro!!!! the time for some events under ilorin are dates not time....... check the time column

**Comment by PrimeFord** [comment] 2023-07-12 09:02
> @kaf-lamed-beyt you can reassign it to @PrimeFord let him work on it. I will find some other issue.
thanks bro... its an honor from you chief

**Comment by kaf-lamed-beyt** [comment] 2023-07-12 10:10
> @kaf-lamed-beyt you can reassign it to @PrimeFord let him work on it. I will find some other issue.

Ayy! I'll do that now. Thanks

**Comment by kaf-lamed-beyt** [comment] 2023-07-12 10:14
> @kaf-lamed-beyt i think you should setup a Github action that lets people assign an issue to them self, when they type a specific command.
> 
> so others can see that the task has been assigned

My chief @yhoungdev, I think we may end up running into so many crisis in the future if we adopt this 😄.

Think about a lot of people trying to assign themselves to a particular issue. That said, I think it'll give the maintainers the ability to ensure decorum and order. 

If someone wants to work on an issue, they asked to be assigned. If they're unable to continue, they'd state that they cannot, just as my chief @DeveloperAspire did.

I think this would even help improve the sanity of the maintainers. Makes sense? 🙏🏼

**Comment by kaf-lamed-beyt** [comment] 2023-07-12 10:16
@PrimeFord, I'm assigning this to you now. 

Please fix the date issues in the Ilorin events too, if you remember when they happened.

**Comment by yhoungdev** [comment] 2023-07-12 11:36
> 

when a task has already been assigned, it cant be assigned to someone else, except its been unassigned. 

and if they cant work on it again they can comment and unassigned their self

**Comment by kaf-lamed-beyt** [comment] 2023-07-12 11:40
Oh okay. I guess that makes sense now then. 

Please go on now. Thanks chief! 🤲🏽

**Comment by yhoungdev** [comment] 2023-07-12 11:52
cool and also can i add issue templates?
 this will make it easy to track issues like 
* Issue description 
* Feature request and others 

something like this.
this is a sample template for feature request 
![Screenshot from 2023-07-12 12-50-07](https://github.com/kaf-lamed-beyt/ng-tech-events/assets/54102389/f4dfeb32-bc82-4760-9377-4cf7d799ef17)

this is the issue template, it gives the person raising the issue a clear way to put it 
![Screenshot from 2023-07-12 12-50-19](https://github.com/kaf-lamed-beyt/ng-tech-events/assets/54102389/c96415ba-c14d-4575-81d1-4fb0b5c903f6)

**Comment by kaf-lamed-beyt** [comment] 2023-07-12 12:16
Yes, my chief! Please go on 😃 🙌🏼

**Comment by PrimeFord** [comment] 2023-07-12 13:53
> Yes, my chief! Please go on 😃 🙌🏼
![fix](https://github.com/kaf-lamed-beyt/ng-tech-events/assets/115805335/f9621459-2053-4e38-92e8-c47c8f76c49e)

boss permission denied

**Comment by kaf-lamed-beyt** [comment] 2023-07-12 17:43
@PrimeFord, you have to fork the repo 😃 

There are some instructions [here](https://github.com/kaf-lamed-beyt/ng-tech-events/blob/master/CONTRIBUTING.md#getting-started)

**Comment by yhoungdev** [comment] 2023-07-12 17:51
@PrimeFord you have to create a fork of the repo first

**Comment by PrimeFord** [comment] 2023-07-13 05:33
Did that already….

**Comment by Petsamuel** [comment] 2023-07-13 05:46
> Did that already….

Issue: You are trying to push directly to master repo
and not your forked repo.

Solution: Create a new remote bridge.
Then commit, and push your change to the new repo remote bridge you created.

**Closed** 2023-07-15 05:54 UTC
Labels: enhancement, good first issue

**Comment by PrimeFord** [comment] 2023-07-15 07:10
![missed](https://github.com/kaf-lamed-beyt/ng-tech-events/assets/115805335/7ef4156e-7fda-4fd6-9e01-0a14a8cde027)
boss by the way I missed this, wanted to confirm the year first.... so I checked their site.... imma fix it now

**Comment by kaf-lamed-beyt** [comment] 2023-07-15 07:13
Oops! Can you create a new PR that fixes this? @PrimeFord?
